### ISSUE TITLE
Mobile - Scrolling doesn't scroll the modal, just the background

### ISSUE THREAD

**Issue by joryeugene** [benhowell/re-frame-modal#1]
When viewing a modal on a mobile device, the background behind the modal is scrolled. Also, if there is content in the modal that doesn't fit on the mobile device screen, it is not viewable because you are not able to scroll to see it.

**Comment by benhowell** [comment]
Hi @joryeugene, you need to set  `overflow-x: auto;` on your child component.

The example modals I've included are just examples, you still need to style whatever you want to show in the modal.

Let's use the hello modal example, and add scrolling to the content of the modal:

```clojure
(defn- hello []
  [:div
   {:style {:background-color "white"
            :padding          "16px"
            :border-radius    "6px"
            :overflow-x "auto"
            :text-align "center"}} "Hello modal!"])
```
